export interface ICity {
  id: string;
  name: string;
}

export const cities = [
  { id: '1', name: 'Aceh Barat' },
  { id: '2', name: 'Aceh Barat Daya' },
  { id: '3', name: 'Aceh Besar' },
  { id: '4', name: 'Aceh Jaya' },
  { id: '5', name: 'Aceh Selatan' },
  { id: '6', name: 'Aceh Singkil' },
  { id: '7', name: 'Aceh Tamiang' },
  { id: '8', name: 'Aceh Tengah' },
  { id: '9', name: 'Aceh Tenggara' },
  { id: '10', name: 'Aceh Timur' },
  { id: '11', name: 'Aceh Utara' },
  { id: '12', name: 'Agam' },
  { id: '13', name: 'Alor' },
  { id: '14', name: 'Ambon' },
  { id: '15', name: 'Asahan' },
  { id: '16', name: 'Asmat' },
  { id: '17', name: 'Badung' },
  { id: '18', name: 'Balangan' },
  { id: '19', name: 'Balikpapan' },
  { id: '20', name: 'Banda Aceh' },
  { id: '21', name: 'Bandar Lampung' },
  { id: '22', name: 'Bandung Kabupaten' }, // Kabupaten
  { id: '23', name: 'Bandung Kota' }, // Kota
  { id: '24', name: 'Bandung Barat' },
  { id: '25', name: 'Banggai' },
  { id: '26', name: 'Banggai Kepulauan' },
  { id: '27', name: 'Bangka' },
  { id: '28', name: 'Bangka Barat' },
  { id: '29', name: 'Bangka Selatan' },
  { id: '30', name: 'Bangka Tengah' },
  { id: '31', name: 'Bangkalan' },
  { id: '32', name: 'Bangli' },
  { id: '33', name: 'Banjar Kabupaten' }, // Kabupaten
  { id: '34', name: 'Banjar Kota' }, // Kota
  { id: '35', name: 'Banjarbaru' },
  { id: '36', name: 'Banjarmasin' },
  { id: '37', name: 'Banjarnegara' },
  { id: '38', name: 'Bantaeng' },
  { id: '39', name: 'Bantul' },
  { id: '40', name: 'Banyuasin' },
  { id: '41', name: 'Banyumas' },
  { id: '42', name: 'Banyuwangi' },
  { id: '43', name: 'Barito Kuala' },
  { id: '44', name: 'Barito Selatan' },
  { id: '45', name: 'Barito Timur' },
  { id: '46', name: 'Barito Utara' },
  { id: '47', name: 'Barru' },
  { id: '48', name: 'Batam' },
  { id: '49', name: 'Batang' },
  { id: '50', name: 'Batang Hari' },
  { id: '51', name: 'Batu' },
  { id: '52', name: 'Batu Bara' },
  { id: '53', name: 'Bau-Bau' },
  { id: '54', name: 'Bekasi Kabupaten' }, // Kabupaten
  { id: '55', name: 'Bekasi Kota' }, // Kota
  { id: '56', name: 'Belitung' },
  { id: '57', name: 'Belitung Timur' },
  { id: '58', name: 'Belu' },
  { id: '59', name: 'Bener Meriah' },
  { id: '60', name: 'Bengkalis' },
  { id: '61', name: 'Bengkayang' },
  { id: '62', name: 'Bengkulu Kota' }, // Kota
  { id: '63', name: 'Bengkulu Selatan' },
  { id: '64', name: 'Bengkulu Tengah' },
  { id: '65', name: 'Bengkulu Utara' },
  { id: '66', name: 'Berau' },
  { id: '67', name: 'Biak Numfor' },
  { id: '68', name: 'Bima Kabupaten' }, // Kabupaten
  { id: '69', name: 'Bima Kota' }, // Kota
  { id: '70', name: 'Binjai' },
  { id: '71', name: 'Bintan' },
  { id: '72', name: 'Bireuen' },
  { id: '73', name: 'Bitung' },
  { id: '74', name: 'Blitar Kabupaten' }, // Kabupaten
  { id: '75', name: 'Blitar Kota' }, // Kota
  { id: '76', name: 'Blora' },
  { id: '77', name: 'Boalemo' },
  { id: '78', name: 'Bogor Kabupaten' }, // Kabupaten
  { id: '79', name: 'Bogor Kota' }, // Kota
  { id: '80', name: 'Bojonegoro' },
  { id: '81', name: 'Bolaang Mongondow (Bolmong)' },
  { id: '82', name: 'Bolaang Mongondow Selatan' },
  { id: '83', name: 'Bolaang Mongondow Timur' },
  { id: '84', name: 'Bolaang Mongondow Utara' },
  { id: '85', name: 'Bombana' },
  { id: '86', name: 'Bondowoso' },
  { id: '87', name: 'Bone' },
  { id: '88', name: 'Bone Bolango' },
  { id: '89', name: 'Bontang' },
  { id: '90', name: 'Boven Digoel' },
  { id: '91', name: 'Boyolali' },
  { id: '92', name: 'Brebes' },
  { id: '93', name: 'Bukittinggi' },
  { id: '94', name: 'Buleleng' },
  { id: '95', name: 'Bulukumba' },
  { id: '96', name: 'Bulungan (Bulongan)' },
  { id: '97', name: 'Bungo' },
  { id: '98', name: 'Buol' },
  { id: '99', name: 'Buru' },
  { id: '100', name: 'Buru Selatan' },
  { id: '101', name: 'Buton' },
  { id: '102', name: 'Buton Utara' },
  { id: '103', name: 'Ciamis' },
  { id: '104', name: 'Cianjur' },
  { id: '105', name: 'Cilacap' },
  { id: '106', name: 'Cilegon' },
  { id: '107', name: 'Cimahi' },
  { id: '108', name: 'Cirebon Kabupaten' }, // Kabupaten
  { id: '109', name: 'Cirebon Kota' }, // Kota
  { id: '110', name: 'Dairi' },
  { id: '111', name: 'Deiyai (Deliyai)' },
  { id: '112', name: 'Deli Serdang' },
  { id: '113', name: 'Demak' },
  { id: '114', name: 'Denpasar' },
  { id: '115', name: 'Depok' },
  { id: '116', name: 'Dharmasraya' },
  { id: '117', name: 'Dogiyai' },
  { id: '118', name: 'Dompu' },
  { id: '119', name: 'Donggala' },
  { id: '120', name: 'Dumai' },
  { id: '121', name: 'Empat Lawang' },
  { id: '122', name: 'Ende' },
  { id: '123', name: 'Enrekang' },
  { id: '124', name: 'Fakfak' },
  { id: '125', name: 'Flores Timur' },
  { id: '126', name: 'Garut' },
  { id: '127', name: 'Gayo Lues' },
  { id: '128', name: 'Gianyar' },
  { id: '129', name: 'Gorontalo Kabupaten' }, // Kabupaten
  { id: '130', name: 'Gorontalo Kota' }, // Kota
  { id: '131', name: 'Gorontalo Utara' },
  { id: '132', name: 'Gowa' },
  { id: '133', name: 'Gresik' },
  { id: '134', name: 'Grobogan' },
  { id: '135', name: 'Gunung Kidul' },
  { id: '136', name: 'Gunung Mas' },
  { id: '137', name: 'Gunungsitoli' },
  { id: '138', name: 'Halmahera Barat' },
  { id: '139', name: 'Halmahera Selatan' },
  { id: '140', name: 'Halmahera Tengah' },
  { id: '141', name: 'Halmahera Timur' },
  { id: '142', name: 'Halmahera Utara' },
  { id: '143', name: 'Hulu Sungai Selatan' },
  { id: '144', name: 'Hulu Sungai Tengah' },
  { id: '145', name: 'Hulu Sungai Utara' },
  { id: '146', name: 'Humbang Hasundutan' },
  { id: '147', name: 'Indragiri Hilir' },
  { id: '148', name: 'Indragiri Hulu' },
  { id: '149', name: 'Indramayu' },
  { id: '150', name: 'Intan Jaya' },
  { id: '151', name: 'Jakarta Barat' },
  { id: '152', name: 'Jakarta Pusat' },
  { id: '153', name: 'Jakarta Selatan' },
  { id: '154', name: 'Jakarta Timur' },
  { id: '155', name: 'Jakarta Utara' },
  { id: '156', name: 'Jambi' },
  { id: '157', name: 'Jayapura Kabupaten' }, // Kabupaten
  { id: '158', name: 'Jayapura Kota' }, // Kota
  { id: '159', name: 'Jayawijaya' },
  { id: '160', name: 'Jember' },
  { id: '161', name: 'Jembrana' },
  { id: '162', name: 'Jeneponto' },
  { id: '163', name: 'Jepara' },
  { id: '164', name: 'Jombang' },
  { id: '165', name: 'Kaimana' },
  { id: '166', name: 'Kampar' },
  { id: '167', name: 'Kapuas' },
  { id: '168', name: 'Kapuas Hulu' },
  { id: '169', name: 'Karanganyar' },
  { id: '170', name: 'Karangasem' },
  { id: '171', name: 'Karawang' },
  { id: '172', name: 'Karimun' },
  { id: '173', name: 'Karo' },
  { id: '174', name: 'Katingan' },
  { id: '175', name: 'Kaur' },
  { id: '176', name: 'Kayong Utara' },
  { id: '177', name: 'Kebumen' },
  { id: '178', name: 'Kediri Kabupaten' }, // Kabupaten
  { id: '179', name: 'Kediri Kota' }, // Kota
  { id: '180', name: 'Keerom' },
  { id: '181', name: 'Kendal' },
  { id: '182', name: 'Kendari' },
  { id: '183', name: 'Kepahiang' },
  { id: '184', name: 'Kepulauan Anambas' },
  { id: '185', name: 'Kepulauan Aru' },
  { id: '186', name: 'Kepulauan Mentawai' },
  { id: '187', name: 'Kepulauan Meranti' },
  { id: '188', name: 'Kepulauan Sangihe' },
  { id: '189', name: 'Kepulauan Seribu' },
  { id: '190', name: 'Kepulauan Siau Tagulandang Biaro (Sitaro)' },
  { id: '191', name: 'Kepulauan Sula' },
  { id: '192', name: 'Kepulauan Talaud' },
  { id: '193', name: 'Kepulauan Yapen (Yapen Waropen)' },
  { id: '194', name: 'Kerinci' },
  { id: '195', name: 'Ketapang' },
  { id: '196', name: 'Klaten' },
  { id: '197', name: 'Klungkung' },
  { id: '198', name: 'Kolaka' },
  { id: '199', name: 'Kolaka Utara' },
  { id: '200', name: 'Konawe' },
  { id: '201', name: 'Konawe Selatan' },
  { id: '202', name: 'Konawe Utara' },
  { id: '203', name: 'Kotabaru' },
  { id: '204', name: 'Kotamobagu' },
  { id: '205', name: 'Kotawaringin Barat' },
  { id: '206', name: 'Kotawaringin Timur' },
  { id: '207', name: 'Kuantan Singingi' },
  { id: '208', name: 'Kubu Raya' },
  { id: '209', name: 'Kudus' },
  { id: '210', name: 'Kulon Progo' },
  { id: '211', name: 'Kuningan' },
  { id: '212', name: 'Kupang Kabupaten' }, // Kabupaten
  { id: '213', name: 'Kupang Kota' }, // Kota
  { id: '214', name: 'Kutai Barat' },
  { id: '215', name: 'Kutai Kartanegara' },
  { id: '216', name: 'Kutai Timur' },
  { id: '217', name: 'Labuhan Batu' },
  { id: '218', name: 'Labuhan Batu Selatan' },
  { id: '219', name: 'Labuhan Batu Utara' },
  { id: '220', name: 'Lahat' },
  { id: '221', name: 'Lamandau' },
  { id: '222', name: 'Lamongan' },
  { id: '223', name: 'Lampung Barat' },
  { id: '224', name: 'Lampung Selatan' },
  { id: '225', name: 'Lampung Tengah' },
  { id: '226', name: 'Lampung Timur' },
  { id: '227', name: 'Lampung Utara' },
  { id: '228', name: 'Landak' },
  { id: '229', name: 'Langkat' },
  { id: '230', name: 'Langsa' },
  { id: '231', name: 'Lanny Jaya' },
  { id: '232', name: 'Lebak' },
  { id: '233', name: 'Lebong' },
  { id: '234', name: 'Lembata' },
  { id: '235', name: 'Lhokseumawe' },
  { id: '236', name: 'Lima Puluh Koto/Kota' },
  { id: '237', name: 'Lingga' },
  { id: '238', name: 'Lombok Barat' },
  { id: '239', name: 'Lombok Tengah' },
  { id: '240', name: 'Lombok Timur' },
  { id: '241', name: 'Lombok Utara' },
  { id: '242', name: 'Lubuk Linggau' },
  { id: '243', name: 'Lumajang' },
  { id: '244', name: 'Luwu' },
  { id: '245', name: 'Luwu Timur' },
  { id: '246', name: 'Luwu Utara' },
  { id: '247', name: 'Madiun Kabupaten' }, // Kabupaten
  { id: '248', name: 'Madiun Kota' }, // Kota
  { id: '249', name: 'Magelang Kabupaten' }, // Kabupaten
  { id: '250', name: 'Magelang Kota' }, // Kota
  { id: '251', name: 'Magetan' },
  { id: '252', name: 'Majalengka' },
  { id: '253', name: 'Majene' },
  { id: '254', name: 'Makassar' },
  { id: '255', name: 'Malang Kabupaten' }, // Kabupaten
  { id: '256', name: 'Malang Kota' }, // Kota
  { id: '257', name: 'Malinau' },
  { id: '258', name: 'Maluku Barat Daya' },
  { id: '259', name: 'Maluku Tengah' },
  { id: '260', name: 'Maluku Tenggara' },
  { id: '261', name: 'Maluku Tenggara Barat' },
  { id: '262', name: 'Mamasa' },
  { id: '263', name: 'Mamberamo Raya' },
  { id: '264', name: 'Mamberamo Tengah' },
  { id: '265', name: 'Mamuju' },
  { id: '266', name: 'Mamuju Utara' },
  { id: '267', name: 'Manado' },
  { id: '268', name: 'Mandailing Natal' },
  { id: '269', name: 'Manggarai' },
  { id: '270', name: 'Manggarai Barat' },
  { id: '271', name: 'Manggarai Timur' },
  { id: '272', name: 'Manokwari' },
  { id: '273', name: 'Manokwari Selatan' },
  { id: '274', name: 'Mappi' },
  { id: '275', name: 'Maros' },
  { id: '276', name: 'Mataram' },
  { id: '277', name: 'Maybrat' },
  { id: '278', name: 'Medan' },
  { id: '279', name: 'Melawi' },
  { id: '280', name: 'Merangin' },
  { id: '281', name: 'Merauke' },
  { id: '282', name: 'Mesuji' },
  { id: '283', name: 'Metro' },
  { id: '284', name: 'Mimika' },
  { id: '285', name: 'Minahasa' },
  { id: '286', name: 'Minahasa Selatan' },
  { id: '287', name: 'Minahasa Tenggara' },
  { id: '288', name: 'Minahasa Utara' },
  { id: '289', name: 'Mojokerto Kabupaten' }, // Kabupaten
  { id: '290', name: 'Mojokerto Kota' }, // Kota
  { id: '291', name: 'Morowali' },
  { id: '292', name: 'Muara Enim' },
  { id: '293', name: 'Muaro Jambi' },
  { id: '294', name: 'Muko Muko' },
  { id: '295', name: 'Muna' },
  { id: '296', name: 'Murung Raya' },
  { id: '297', name: 'Musi Banyuasin' },
  { id: '298', name: 'Musi Rawas' },
  { id: '299', name: 'Nabire' },
  { id: '300', name: 'Nagan Raya' },
  { id: '301', name: 'Nagekeo' },
  { id: '302', name: 'Natuna' },
  { id: '303', name: 'Nduga' },
  { id: '304', name: 'Ngada' },
  { id: '305', name: 'Nganjuk' },
  { id: '306', name: 'Ngawi' },
  { id: '307', name: 'Nias' },
  { id: '308', name: 'Nias Barat' },
  { id: '309', name: 'Nias Selatan' },
  { id: '310', name: 'Nias Utara' },
  { id: '311', name: 'Nunukan' },
  { id: '312', name: 'Ogan Ilir' },
  { id: '313', name: 'Ogan Komering Ilir' },
  { id: '314', name: 'Ogan Komering Ulu' },
  { id: '315', name: 'Ogan Komering Ulu Selatan' },
  { id: '316', name: 'Ogan Komering Ulu Timur' },
  { id: '317', name: 'Pacitan' },
  { id: '318', name: 'Padang' },
  { id: '319', name: 'Padang Lawas' },
  { id: '320', name: 'Padang Lawas Utara' },
  { id: '321', name: 'Padang Panjang' },
  { id: '322', name: 'Padang Pariaman' },
  { id: '323', name: 'Padang Sidempuan' },
  { id: '324', name: 'Pagar Alam' },
  { id: '325', name: 'Pakpak Bharat' },
  { id: '326', name: 'Palangka Raya' },
  { id: '327', name: 'Palembang' },
  { id: '328', name: 'Palopo' },
  { id: '329', name: 'Palu' },
  { id: '330', name: 'Pamekasan' },
  { id: '331', name: 'Pandeglang' },
  { id: '332', name: 'Pangandaran' },
  { id: '333', name: 'Pangkajene Kepulauan' },
  { id: '334', name: 'Pangkal Pinang' },
  { id: '335', name: 'Paniai' },
  { id: '336', name: 'Parepare' },
  { id: '337', name: 'Pariaman' },
  { id: '338', name: 'Parigi Moutong' },
  { id: '339', name: 'Pasaman' },
  { id: '340', name: 'Pasaman Barat' },
  { id: '341', name: 'Paser' },
  { id: '342', name: 'Pasuruan Kabupaten' }, // Kabupaten
  { id: '343', name: 'Pasuruan Kota' }, // Kota
  { id: '344', name: 'Pati' },
  { id: '345', name: 'Payakumbuh' },
  { id: '346', name: 'Pegunungan Arfak' },
  { id: '347', name: 'Pegunungan Bintang' },
  { id: '348', name: 'Pekalongan Kabupaten' }, // Kabupaten
  { id: '349', name: 'Pekalongan Kota' }, // Kota
  { id: '350', name: 'Pekanbaru' },
  { id: '351', name: 'Pelalawan' },
  { id: '352', name: 'Pemalang' },
  { id: '353', name: 'Pematang Siantar' },
  { id: '354', name: 'Penajam Paser Utara' },
  { id: '355', name: 'Pesawaran' },
  { id: '356', name: 'Pesisir Barat' },
  { id: '357', name: 'Pesisir Selatan' },
  { id: '358', name: 'Pidie' },
  { id: '359', name: 'Pidie Jaya' },
  { id: '360', name: 'Pinrang' },
  { id: '361', name: 'Pohuwato' },
  { id: '362', name: 'Polewali Mandar' },
  { id: '363', name: 'Ponorogo' },
  { id: '364', name: 'Pontianak Kabupaten' }, // Kabupaten
  { id: '365', name: 'Pontianak Kota' }, // Kota
  { id: '366', name: 'Poso' },
  { id: '367', name: 'Prabumulih' },
  { id: '368', name: 'Pringsewu' },
  { id: '369', name: 'Probolinggo Kabupaten' }, // Kabupaten
  { id: '370', name: 'Probolinggo Kota' }, // Kota
  { id: '371', name: 'Pulang Pisau' },
  { id: '372', name: 'Pulau Morotai' },
  { id: '373', name: 'Puncak' },
  { id: '374', name: 'Puncak Jaya' },
  { id: '375', name: 'Purbalingga' },
  { id: '376', name: 'Purwakarta' },
  { id: '377', name: 'Purworejo' },
  { id: '378', name: 'Raja Ampat' },
  { id: '379', name: 'Rejang Lebong' },
  { id: '380', name: 'Rembang' },
  { id: '381', name: 'Rokan Hilir' },
  { id: '382', name: 'Rokan Hulu' },
  { id: '383', name: 'Rote Ndao' },
  { id: '384', name: 'Sabang' },
  { id: '385', name: 'Sabu Raijua' },
  { id: '386', name: 'Salatiga' },
  { id: '387', name: 'Samarinda' },
  { id: '388', name: 'Sambas' },
  { id: '389', name: 'Samosir' },
  { id: '390', name: 'Sampang' },
  { id: '391', name: 'Sanggau' },
  { id: '392', name: 'Sarmi' },
  { id: '393', name: 'Sarolangun' },
  { id: '394', name: 'Sawah Lunto' },
  { id: '395', name: 'Sekadau' },
  { id: '396', name: 'Selayar (Kepulauan Selayar)' },
  { id: '397', name: 'Seluma' },
  { id: '398', name: 'Semarang Kabupaten' }, // Kabupaten
  { id: '399', name: 'Semarang Kota' }, // Kota
  { id: '400', name: 'Seram Bagian Barat' },
  { id: '401', name: 'Seram Bagian Timur' },
  { id: '402', name: 'Serang Kabupaten' }, // Kabupaten
  { id: '403', name: 'Serang Kota' }, // Kota
  { id: '404', name: 'Serdang Bedagai' },
  { id: '405', name: 'Seruyan' },
  { id: '406', name: 'Siak' },
  { id: '407', name: 'Sibolga' },
  { id: '408', name: 'Sidenreng Rappang/Rapang' },
  { id: '409', name: 'Sidoarjo' },
  { id: '410', name: 'Sigi' },
  { id: '411', name: 'Sijunjung (Sawah Lunto Sijunjung)' },
  { id: '412', name: 'Sikka' },
  { id: '413', name: 'Simalungun' },
  { id: '414', name: 'Simeulue' },
  { id: '415', name: 'Singkawang' },
  { id: '416', name: 'Sinjai' },
  { id: '417', name: 'Sintang' },
  { id: '418', name: 'Situbondo' },
  { id: '419', name: 'Sleman' },
  { id: '420', name: 'Solok Kabupaten' }, // Kabupaten
  { id: '421', name: 'Solok Kota' }, // Kota
  { id: '422', name: 'Solok Selatan' },
  { id: '423', name: 'Soppeng' },
  { id: '424', name: 'Sorong Kabupaten' }, // Kabupaten
  { id: '425', name: 'Sorong Kota' }, // Kota
  { id: '426', name: 'Sorong Selatan' },
  { id: '427', name: 'Sragen' },
  { id: '428', name: 'Subang' },
  { id: '429', name: 'Subulussalam' },
  { id: '430', name: 'Sukabumi Kabupaten' }, // Kabupaten
  { id: '431', name: 'Sukabumi Kota' }, // Kota
  { id: '432', name: 'Sukamara' },
  { id: '433', name: 'Sukoharjo' },
  { id: '434', name: 'Sumba Barat' },
  { id: '435', name: 'Sumba Barat Daya' },
  { id: '436', name: 'Sumba Tengah' },
  { id: '437', name: 'Sumba Timur' },
  { id: '438', name: 'Sumbawa' },
  { id: '439', name: 'Sumbawa Barat' },
  { id: '440', name: 'Sumedang' },
  { id: '441', name: 'Sumenep' },
  { id: '442', name: 'Sungaipenuh' },
  { id: '443', name: 'Supiori' },
  { id: '444', name: 'Surabaya' },
  { id: '445', name: 'Surakarta (Solo)' },
  { id: '446', name: 'Tabalong' },
  { id: '447', name: 'Tabanan' },
  { id: '448', name: 'Takalar' },
  { id: '449', name: 'Tambrauw' },
  { id: '450', name: 'Tana Tidung' },
  { id: '451', name: 'Tana Toraja' },
  { id: '452', name: 'Tanah Bumbu' },
  { id: '453', name: 'Tanah Datar' },
  { id: '454', name: 'Tanah Laut' },
  { id: '455', name: 'Tangerang Kabupaten' }, // Kabupaten
  { id: '456', name: 'Tangerang Kota' }, // Kota
  { id: '457', name: 'Tangerang Selatan' },
  { id: '458', name: 'Tanggamus' },
  { id: '459', name: 'Tanjung Balai' },
  { id: '460', name: 'Tanjung Jabung Barat' },
  { id: '461', name: 'Tanjung Jabung Timur' },
  { id: '462', name: 'Tanjung Pinang' },
  { id: '463', name: 'Tapanuli Selatan' },
  { id: '464', name: 'Tapanuli Tengah' },
  { id: '465', name: 'Tapanuli Utara' },
  { id: '466', name: 'Tapin' },
  { id: '467', name: 'Tarakan' },
  { id: '468', name: 'Tasikmalaya Kabupaten' }, // Kabupaten
  { id: '469', name: 'Tasikmalaya Kota' }, // Kota
  { id: '470', name: 'Tebing Tinggi' },
  { id: '471', name: 'Tebo' },
  { id: '472', name: 'Tegal Kabupaten' }, // Kabupaten
  { id: '473', name: 'Tegal Kota' }, // Kota
  { id: '474', name: 'Teluk Bintuni' },
  { id: '475', name: 'Teluk Wondama' },
  { id: '476', name: 'Temanggung' },
  { id: '477', name: 'Ternate' },
  { id: '478', name: 'Tidore Kepulauan' },
  { id: '479', name: 'Timor Tengah Selatan' },
  { id: '480', name: 'Timor Tengah Utara' },
  { id: '481', name: 'Toba Samosir' },
  { id: '482', name: 'Tojo Una-Una' },
  { id: '483', name: 'Toli-Toli' },
  { id: '484', name: 'Tolikara' },
  { id: '485', name: 'Tomohon' },
  { id: '486', name: 'Toraja Utara' },
  { id: '487', name: 'Trenggalek' },
  { id: '488', name: 'Tual' },
  { id: '489', name: 'Tuban' },
  { id: '490', name: 'Tulang Bawang' },
  { id: '491', name: 'Tulang Bawang Barat' },
  { id: '492', name: 'Tulungagung' },
  { id: '493', name: 'Wajo' },
  { id: '494', name: 'Wakatobi' },
  { id: '495', name: 'Waropen' },
  { id: '496', name: 'Way Kanan' },
  { id: '497', name: 'Wonogiri' },
  { id: '498', name: 'Wonosobo' },
  { id: '499', name: 'Yahukimo' },
  { id: '500', name: 'Yalimo' },
  { id: '501', name: 'Yogyakarta' },
];
